GET http://localhost:3001/api/

###
DELETE http://localhost:3001/api/persons/4 
###

POST http://localhost:3001/api/persons

Content-Type: application/json

{
  "name": "John",
  "number": "34204802384",
  "id":0
}
###